Created routes for editing and deleting a device
Drizzle-Technologies/webapp-apis pull request #1
Opened 2021-02-17 14:55 UTC by giovana-costa

routes to edit and delete created

2021-02-17 15:38 UTC, joao-fb commented on src/routes.py
> +    new_area = float(device_data["NewArea"])
Eu trocaria isso aqui por
```suggestion
    new_area = int(device_data["NewArea"])
```

Os dados de área são armazenados como int.

2021-02-17 15:40 UTC, joao-fb commented on src/routes.py
> +@api.route('device/edit', methods=["PATCH"])
Esqueci de colocar na especificação, mas as rotas são protegidas

2021-02-17 15:42 UTC, joao-fb commented on src/routes.py
> +@api.route('device/edit', methods=["PATCH"])
Adicionar quebra de linha (duas linhas para a função de cima)

2021-02-17 15:42 UTC, joao-fb commented on src/routes.py
> +@api.route('device/delete', methods=["DELETE"])
Proteção de rota

2021-02-17 15:47 UTC, joao-fb commented on src/routes.py
> +    ID_device = device_data["DeviceID"]
Precisamos trocar por idList, recebe lista de IDs.

2021-02-17 15:47 UTC, joao-fb commented on src/routes.py
> +    devices_dao.delete_device(ID_device)
E aqui precisamos de um for para deletar cada ID. Depois melhoro isso com um método DAO que recebe uma lista de IDs.

2021-02-17 15:48 UTC, joao-fb requested changes
Considerar comentários feitos para realizar as mudanças. Depois só dar commit e push na branch edit/delete

2021-02-17 16:55 UTC, giovana-costa commented on src/routes.py
> +    new_area = float(device_data["NewArea"])
Mas a área não poderia ser um valor quebrado?

2021-02-17 22:32 UTC, joao-fb requested changes
Tudo certo! To aprovando aqui!

2021-02-17 22:32 UTC, joao-fb commented on src/routes.py
> +    new_area = float(device_data["NewArea"])
```suggestion
    new_area = int(device_data["NewArea"])
```

Ainda precisa mudar isso aqui, Gi!

2021-02-18 03:16 UTC, joao-fb requested changes
Falta pouco hehe

2021-02-18 03:16 UTC, joao-fb commented on src/routes.py
> +    ID_device = device_data["DeviceID"]
```suggestion
    ID_device = device_data["deviceID"]
```
```suggestion
    ID_device = device_data["DeviceID"]
```

2021-02-18 03:23 UTC, joao-fb approved these changes

2021-02-18 03:23 UTC, merged